/**
 * road.ts
 *
 * Builds and stores the array of road segments that define the track layout.
 *
 * Key idea — pseudo-3D road geometry:
 *   The road is modelled as a long array of flat "slices", each SEGMENT_LENGTH
 *   world units deep.  Every slice knows its horizontal curve value and its
 *   vertical Y position.  The renderer projects each slice through a virtual
 *   camera to produce the 2-D trapezoid the player sees on screen.
 *
 *   Think of it like a deck of cards laid in a line stretching into the distance.
 *   Each card is one RoadSegment.  Bend or tilt the line of cards and you get
 *   curves and hills.
 */

import { RoadSegment, ProjectedPoint, SegmentColor, SpriteFamily, SpriteInstance } from './types';
import { SEGMENT_LENGTH, COLORS, ROAD_CURVE, ROAD_HILL } from './constants';

// ── Easing functions ──────────────────────────────────────────────────────────
//
// "Easing" makes transitions smooth — instead of snapping instantly from
// value A to value B, we glide between them following a curved path.
// percent goes from 0.0 (start) to 1.0 (end).

/**
 * Eases IN: starts slow, ends fast.  Like a car pulling away from rest.
 * Uses a quadratic curve: slow at the beginning, accelerating toward the end.
 *
 * @param a       - Start value.
 * @param b       - End value.
 * @param percent - Progress from 0 (at a) to 1 (at b).
 * @returns Interpolated value between a and b.
 */
function easeIn(a: number, b: number, percent: number): number
{
  return a + (b - a) * Math.pow(percent, 2);
}

/**
 * Eases IN and OUT: starts slow, accelerates, then slows again at the end.
 * Uses a cosine curve — the smoothest possible S-shaped transition.
 * Used for both curve and hill height changes so bends feel gradual.
 *
 * @param a       - Start value.
 * @param b       - End value.
 * @param percent - Progress from 0 (at a) to 1 (at b).
 * @returns Interpolated value between a and b.
 */
function easeInOut(a: number, b: number, percent: number): number
{
  return a + (b - a) * ((-Math.cos(percent * Math.PI) / 2) + 0.5);
}

// ── Internal factory helpers ───────────────────────────────────────────────────

/**
 * Creates a ProjectedPoint at a given world-space Z and Y position.
 * The screen fields are all zero at creation; the renderer fills them in each frame.
 *
 * @param worldZ - Depth along the road (how far ahead this point is).
 * @param worldY - Height above the flat ground (positive = uphill, negative = downhill).
 * @returns A fresh ProjectedPoint ready to be assigned to p1 or p2.
 */
function makeProjectedPoint(worldZ: number, worldY: number = 0): ProjectedPoint
{
  return {
    world:  { x: 0, y: worldY, z: worldZ },
    screen: { x: 0, y: 0, w: 0, scale: 0 },
  };
}

/**
 * Computes the colour set for segment number i.
 *
 * The road uses two alternating colour bands (groups of 8 segments each).
 * Within each band, the grass and rumble strip share the same light/dark state,
 * while the centre-line lane dash alternates twice as fast (groups of 4)
 * to give the classic dashed-line look as the road scrolls past.
 *
 * @param i - Segment index (0-based).
 * @returns SegmentColor with road, grass, rumble, and lane colours.
 */
function makeColor(i: number): SegmentColor
{
  const band = Math.floor(i / 8) % 2 === 0;
  const dash = Math.floor(i / 8) % 2 === 0;
  return {
    road:   band ? COLORS.ROAD_LIGHT  : COLORS.ROAD_DARK,
    grass:  band ? COLORS.SAND_LIGHT : COLORS.SAND_DARK,
    rumble: band ? COLORS.RUMBLE_RED  : COLORS.RUMBLE_WHITE,
    lane:   dash ? COLORS.LANE        : '',
  };
}

// ── PRNG factory ──────────────────────────────────────────────────────────────

/**
 * Creates a seeded Mulberry32 PRNG with rand / rInt / pick helpers.
 *
 * Pass any 32-bit integer seed.  XOR with Date.now() at the call site for
 * per-load randomisation while keeping distinct seeds for each planter:
 *   makePRNG(Date.now() ^ 0xC00C1E5)
 *
 * Deterministic planters (palms, cactuses) pass a fixed constant directly:
 *   makePRNG(0xDEADBEEF)
 */
function makePRNG(seed: number): {
  rand: () => number;
  rInt: (lo: number, hi: number) => number;
  pick: <T>(arr: readonly T[]) => T;
}
{
  let s = seed >>> 0;
  const rand = (): number =>
  {
    s += 0x6D2B79F5;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967295;
  };
  const rInt = (lo: number, hi: number): number =>
    Math.floor(rand() * (hi - lo + 1)) + lo;
  const pick = <T>(arr: readonly T[]): T =>
    arr[Math.floor(rand() * arr.length)];
  return { rand, rInt, pick };
}

// ── Serialized segment format (for prebuild road-data.ts) ─────────────────────

/**
 * Minimal per-segment data needed to reconstruct a RoadSegment at runtime.
 * Screen-space projection fields (p1.screen, p2.screen) are excluded because
 * the renderer's Pass 1 overwrites them every frame anyway.
 *
 * Generated by `scripts/generate-road.ts` → `src/road-data.ts`.
 */
export interface SerializedSegment
{
  index:   number;
  curve:   number;
  color:   SegmentColor;
  sprites: SpriteInstance[];
  p1y:     number;
  p1z:     number;
  p2y:     number;
  p2z:     number;
}

// ── Road class ────────────────────────────────────────────────────────────────

export class Road
{
  /** All segments in order from start to end of the track. */
  private _segments: RoadSegment[] = [];

  /** Read-only view of the segment array — prevents external mutation. */
  get segments(): readonly RoadSegment[] { return this._segments; }

  /**
   * The Y (height) coordinate of the last segment added.
   * Tracked so that hill sections chain smoothly — each new section
   * starts from where the previous one ended.
   */
  private lastY = 0;

  /**
   * Cross-type board spacing: tracks the last segment index where a board was
   * placed on each side [left, right].  Used by plantBillboards() and
   * plantBigBoards() only — cookie and barney boards use independent gap
   * tracking so they are never starved out by the more frequent og boards.
   */
  private boardLastPlaced: [number, number] = [-999, -999];
  private static readonly MIN_BOARD_GAP = 45;

  /** Builds the track layout immediately on construction. */
  constructor()
  {
    this.resetRoad();
  }

  /** Total number of segments in the track. Used for wrap-around maths. */
  get count(): number
  {
    return this._segments.length;
  }

  // ── Core builder ─────────────────────────────────────────────────────────

  /**
   * Appends one segment to the road array.
   *
   * p1 is the NEAR edge of the strip (worldZ = i * SEGMENT_LENGTH, y = lastY).
   * p2 is the FAR  edge of the strip (worldZ = (i+1) * SEGMENT_LENGTH, y = y).
   *
   * After adding, lastY is updated so the next segment starts at this segment's far end.
   *
   * @param curve - Horizontal bend strength for this segment (0 = straight, 6 = hard).
   * @param y     - World-space height of this segment's far edge.
   */
  private addSegment(curve: number, y: number): void
  {
    const i      = this._segments.length;
    const seg: RoadSegment =
    {
      index: i,
      p1:    makeProjectedPoint(i * SEGMENT_LENGTH, this.lastY),
      p2:    makeProjectedPoint((i + 1) * SEGMENT_LENGTH, y),
      curve,
      color: makeColor(i),
    };
    this.lastY = y;
    this._segments.push(seg);
  }

  /**
   * Adds a road section made of three phases: ease in → hold → ease out.
   *
   * This is what makes OutRun's curves feel natural — instead of snapping to a
   * fixed bend angle, the road gradually winds up to the target curve over
   * `enter` segments, holds it for `hold` segments, then unwinds over `leave`
   * segments.  Hills work the same way along the Y axis.
   *
   * @param enter - Number of segments to ease IN to the target curve/hill.
   * @param hold  - Number of segments to hold the target curve/hill constant.
   * @param leave - Number of segments to ease OUT back to zero curve/flat.
   * @param curve - Target horizontal bend during the hold phase.
   * @param hill  - Total world-unit height change over the whole section.
   *                Positive = uphill, negative = downhill.
   *                Small vs CAMERA_HEIGHT (1000): HIGH=60 ≈ 6% grade.
   */
  private addRoad(
    enter: number, hold: number, leave: number,
    curve: number, hill:  number,
  ): void
  {
    const startY = this.lastY;
    const endY   = startY + hill;   // total rise/fall, NOT per-segment

    for (let n = 0; n < enter; n++)
    {
      this.addSegment(
        easeIn(0, curve, n / enter),
        easeInOut(startY, endY, n / (enter + hold + leave)),
      );
    }
    for (let n = 0; n < hold; n++)
    {
      this.addSegment(
        curve,
        easeInOut(startY, endY, (enter + n) / (enter + hold + leave)),
      );
    }
    for (let n = 0; n < leave; n++)
    {
      this.addSegment(
        easeIn(curve, 0, n / leave),
        easeInOut(startY, endY, (enter + hold + n) / (enter + hold + leave)),
      );
    }
  }

  // ── Track layout ──────────────────────────────────────────────────────────

  /**
   * Clears all existing segments and builds the Nürburgring-inspired track.
   *
   * Layout pillars (like the real Nordschleife):
   *   • Long sustained corners — you're committed for 3–5 seconds.
   *   • Blind crests MID-corner — you cannot see the exit.
   *   • Long straights feed DIRECTLY into hard corners — no time to react.
   *   • Back-to-back hard sections with no breathing room in between.
   *
   * ~1185 segments ≈ 22 seconds at max speed before the lap loops.
   */
  private resetRoad(): void
  {
    this._segments = [];
    this.lastY    = 0;

    const r = (enter: number, hold: number, leave: number, curve: number, hill: number) =>
      this.addRoad(enter, hold, leave, curve, hill);

    const CE = ROAD_CURVE.EASY;   // 2  — gentle sweeper
    const CM = ROAD_CURVE.MEDIUM; // 4  — committed corner
    const CH = ROAD_CURVE.HARD;   // 6  — survival corner
    const HL = ROAD_HILL.LOW;     // 20
    const HM = ROAD_HILL.MEDIUM;  // 40
    const HH = ROAD_HILL.HIGH;    // 60 — blind crest territory

    // ── 1. Launch straight ────────────────────────────────────────────────
    r(1,  38,  1,    0,   0);             // 40 — build speed, feel the car

    // ── 2. Flugplatz — long climbing right sweeper ────────────────────────
    // Feels manageable at first. At full speed it fights you the whole way.
    r(12, 110, 12,   CE,  HL);            // 134 — long easy right, climbing
    r(8,  10,  8,    0, -HL);             // 26  — crest and brief flat

    // ── 3. Hatzenbach — hard uphill left, blind entry ─────────────────────
    // The flat before it lures you in full throttle. Don't.
    r(1,  10,  1,    0,   0);             // 12 — false sense of safety
    r(10, 55, 10,  -CH,  HM);             // 75 — climbing hard left, no exit visible

    // ── 4. Blind downhill right — you're over the crest into a right ──────
    r(10, 45, 10,   CH, -HM);             // 65 — hard right, road drops away fast

    // ── 5. Long downhill straight ─────────────────────────────────────────
    r(1,  58,  1,    0, -HL);             // 60 — speed builds on the descent

    // ── 6. Adenauer Forst — long sustained medium-left sweeper ───────────
    // It keeps going. And going. This is where the drift happens.
    r(15, 120, 15,  -CM,   0);            // 150 — patience and commitment required

    // ── 7. Bergwerk — hard right then immediate hard left ─────────────────
    // Zero gap. If the car is still sliding from the right, the left takes you off.
    r(1,   5,  1,    0,   0);             // 7  — barely a breath
    r(10, 60, 10,   CH,   0);             // 80 — hard right
    r(10, 60, 10,  -CH,   0);             // 80 — hard left, immediate

    // ── 8. Döttinger Höhe — the long flat-out straight ────────────────────
    // Longest straight on the lap. Build maximum speed. You'll pay for it.
    r(1,  110,  1,   0,   0);             // 112 — go flat. All of it.

    // ── 9. Tiergarten — hard right over a blind hill crest ────────────────
    // Maximum speed. Hard right. Climbing. You cannot see the exit. Ever.
    r(10, 76, 10,   CH,  HH);             // 96 — the hardest moment on the lap

    // ── 10. Schwalbenschwanz — left, road drops beneath you ──────────────
    r(10, 64, 10,  -CH, -HM);             // 84 — hard left, downhill, drift trap

    // ── 11. Recovery medium right ─────────────────────────────────────────
    r(10, 44, 10,   CM,   0);             // 64 — breathe. Almost home.

    // ── 12. Finish straight ───────────────────────────────────────────────
    r(1,  78,  1,    0,   0);             // 80 — lap complete. Do it again.

    this.boardLastPlaced = [-999, -999];

    this.plantSigns();
    this.plantShrubs();
    this.plantPalms();
    this.plantBillboards();
    this.plantCookieBoards();
    this.plantBarneyBoards();
    this.plantBigBoards();
    this.plantCactuses();
    this.plantHouses();
  }

  // ── Palm placement ────────────────────────────────────────────────────────

  /**
   * Decorates every segment with palm tree sprites using a Sega-style rubric.
   *
   * ── Design rules ─────────────────────────────────────────────────────────
   *
   *   Hard corners (|curve| ≥ 2)
   *     Outside of the bend gets bent palms (T2_BENT_LEFT or T2_BENT_RIGHT)
   *     in groups of 3 or 5.  Trees within a group are spaced 3–7 segments
   *     apart.  A long cooldown (12–20 segments) separates groups.  30% of
   *     placements add a tall background palm (T6/T7/T10) further off-road.
   *     Inside of the bend gets a sparse scatter of small palms (15% chance,
   *     16–26 segment gaps) so it never feels completely bare.
   *
   *   Gentle curve / straight (|curve| < 2)
   *     Both sides are managed independently.  Each side fires a 38–50%
   *     trigger once its gap counter reaches zero.  A successful trigger
   *     places a cluster of 1 tree (72%) or 2–3 trees (28%) spaced 2–5
   *     segments apart.  25% of clusters use background varieties
   *     (T6/T7/T10) at greater distance; the rest use the general mix at
   *     road-edge distance.  Gaps between clusters: 9–17 segments.
   *
   * ── World-X ranges (ROAD_WIDTH = 2000, road edge = ±2000) ────────────────
   *
   *   Bent corner palms:      outside ±2 500 – 3 100
   *   Straight/close palms:   ±2 500 – 3 500
   *   Background tall palms:  ±3 600 – 5 200
   *   Inside sparse:          ±2 400 – 2 900
   *
   * ── PRNG ─────────────────────────────────────────────────────────────────
   *
   *   Mulberry32 seeded at 0xDEADBEEF — deterministic, same layout every run.
   */
  private plantPalms(): void
  {
    // ── Seeded PRNG (Mulberry32) — deterministic, same layout every run ──
    const { rand, rInt, pick } = makePRNG(0xDEADBEEF);

    // ── Palm variety pools ────────────────────────────────────────────────
    const GENERAL: readonly string[] = [
      'PALM_T1_STRAIGHT', 'PALM_T4_FRUITING',
      'PALM_T6_LUXURIANT', 'PALM_T7_SLENDER',
      'PALM_T8_MEDIUM',   'PALM_T10_LARGE',
    ];
    const BG: readonly string[] = [
      'PALM_T6_LUXURIANT', 'PALM_T7_SLENDER', 'PALM_T10_LARGE',
    ];
    const CLOSE: readonly string[] = [
      'PALM_T3_YOUNG', 'PALM_T8_MEDIUM', 'PALM_T1_STRAIGHT',
    ];

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      // Scale each palm randomly 1×–3× to mimic the size variety in the OG game.
      const scale = 1 + rand() * 2;   // uniform [1, 3]
      (seg.sprites ??= []).push({ id, family: 'palm' as SpriteFamily, worldX, scale });
    };

    // ── Weighted distance sampler ─────────────────────────────────────────────
    //
    // wX(...tiers) — each tier is [weight, minDist, maxDist].
    // Picks a tier by weight, then samples uniformly within it.
    // Returns an unsigned distance; multiply by sign(s) at the call site.
    //
    // Three-tier approach mimics real palm forest structure:
    //   Near  — tight to the road edge (dramatic, arcade feel)
    //   Mid   — comfortable mid-distance (most common)
    //   Far   — deep background silhouettes (depth, atmosphere)
    type Tier = [number, number, number]; // [weight, minDist, maxDist]
    const wX = (...tiers: Tier[]): number =>
    {
      const total = tiers.reduce((s, [w]) => s + w, 0);
      let r = rand() * total;
      for (const [w, lo, hi] of tiers)
      {
        r -= w;
        if (r <= 0) return rInt(lo, hi);
      }
      return rInt(tiers[tiers.length - 1][1], tiers[tiers.length - 1][2]);
    };

    // ── Per-side state ────────────────────────────────────────────────────
    //
    // Index 0 = left side (negative worldX).
    // Index 1 = right side (positive worldX).
    //
    // gap[s]    — segments remaining before next placement is allowed.
    // grpRem[s] — trees left to place in the current corner group.

    const gap    = [rInt(3, 10), rInt(3, 10)];
    const grpRem = [0, 0];

    const sign = (s: number): number => s === 1 ? +1 : -1;

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const curve    = seg.curve;
      const absCurve = Math.abs(curve);

      // Side index for the OUTSIDE of the current bend.
      // Positive curve = turning right.  On a right turn the centre of curvature
      // is to the RIGHT, so centrifugal force pushes the car OUTWARD = LEFT.
      // Outside of a right bend → left side (index 0, negative worldX).
      // Outside of a left  bend → right side (index 1, positive worldX).
      // Confirmed by the physics: playerX -= curve * CENTRIFUGAL * dt pushes
      // the player left (negative) for positive curve = outside is left.
      const outerS = curve >= 0 ? 0 : 1;
      const innerS = 1 - outerS;

      // Tick counters
      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      // ── HARD CORNER — bent palms in groups of 3 or 5 ─────────────────
      if (absCurve >= 2)
      {
        // Outside: fire when gap hits zero
        if (gap[outerS] === 0)
        {
          // Begin a new group if none is active
          if (grpRem[outerS] === 0)
            grpRem[outerS] = rand() < 0.5 ? 3 : 5;

          // Place one bent palm — mostly close, occasionally mid or far back
          const bentId = outerS === 1 ? 'PALM_T2_BENT_LEFT' : 'PALM_T2_BENT_RIGHT';
          plant(seg, bentId, sign(outerS) * wX([4, 2200, 2700], [4, 2700, 3300], [2, 3300, 4200]));
          grpRem[outerS]--;

          // Optionally add a background tall palm — wide range for depth
          if (rand() < 0.30)
            plant(seg, pick(BG), sign(outerS) * wX([3, 3800, 4800], [7, 4800, 7000]));

          // Advance gap: intra-group if more remain, inter-group if done
          gap[outerS] = grpRem[outerS] > 0 ? rInt(3, 7) : rInt(12, 20);
        }

        // Inside: sparse small palms
        if (gap[innerS] === 0 && rand() < 0.15)
        {
          // Inside of corner: hug the road edge with occasional mid-distance
          plant(seg, pick(CLOSE), sign(innerS) * wX([6, 2200, 2700], [4, 2700, 3600]));
          gap[innerS] = rInt(16, 26);
        }
      }

      // ── GENTLE CURVE / STRAIGHT — scattered general palms ────────────
      else
      {
        for (let s = 0; s < 2; s++)
        {
          if (gap[s] > 0) continue;

          // Outside of a gentle curve fires a little more readily
          const isCurve  = absCurve >= 0.5;
          const isOuter  = isCurve && s === outerS;
          const density  = isOuter ? 0.50 : 0.38;

          if (rand() >= density) { gap[s] = rInt(4, 9); continue; }

          // 28% chance: cluster of 2–3; otherwise a single tree
          const clSize = rand() < 0.28 ? rInt(2, 3) : 1;
          for (let c = 0; c < clSize; c++)
          {
            const ti = i + c * rInt(2, 5);
            if (ti >= this._segments.length) break;
            const tseg = this._segments[ti];

            if (rand() < 0.25)
              // Background palms: deep silhouettes spanning a wide range
              plant(tseg, pick(BG),      sign(s) * wX([3, 3400, 4500], [7, 4500, 7000]));
            else
              // General palms: full spread from road edge to mid-background
              plant(tseg, pick(GENERAL), sign(s) * wX([3, 2200, 2700], [5, 2700, 4000], [2, 4000, 5500]));
          }

          gap[s] = rInt(9, 17);
        }
      }
    }

    // ── Deep-background palm scatter (6 000 – 16 000) ────────────────────────
    // Sprinkles palms of all varieties at varying scales far from the road.
    // Uses the same seeded PRNG so the layout is deterministic.
    const ALL: readonly string[] = [
      'PALM_T1_STRAIGHT', 'PALM_T3_YOUNG',
      'PALM_T4_FRUITING',  'PALM_T6_LUXURIANT',
      'PALM_T7_SLENDER',   'PALM_T8_MEDIUM', 'PALM_T10_LARGE',
    ];
    const deepGap = [rInt(2, 6), rInt(2, 6)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg = this._segments[i];
      if (Math.abs(seg.curve) >= 5) continue;

      deepGap[0] = Math.max(0, deepGap[0] - 1);
      deepGap[1] = Math.max(0, deepGap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (deepGap[s] > 0) continue;

        // Drop 1–3 palms spread across the deep range with varied scale
        const count = rInt(1, 3);
        for (let c = 0; c < count; c++)
        {
          const worldX = sign(s) * rInt(6000, 16000);
          const scale  = 0.4 + rand() * 2.2;   // 0.4× tiny to 2.6× towering
          (seg.sprites ??= []).push({ id: pick(ALL), family: 'palm' as SpriteFamily, worldX, scale });
        }

        deepGap[s] = rInt(2, 5);
      }
    }
  }

  // ── Billboard placement ───────────────────────────────────────────────────

  /**
   * Scatters billboard sprites alongside the road.
   * Follows the same pattern as plantPalms() — seeded PRNG, per-side gap counters.
   * One billboard at a time, suppressed on hard corners (|curve| ≥ 4).
   * Themed pools loosely by track section (beagle → tavern → tobacco).
   * Seeded independently (0xCAFEBABE) so palm changes don't reshuffle signs.
   */
  private plantBillboards(): void
  {
    const { rand, rInt, pick } = makePRNG(0xCAFEBABE);

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'billboard' as SpriteFamily, worldX, scale: 1 });
    };

    const BEAGLE:  readonly string[] = ['BILLBOARD_BEAGLE_PETS', 'BILLBOARD_ADOPT_BEAGLE', 'BILLBOARD_BEAGLE_POWER', 'BILLBOARD_LOYAL_FRIENDLY'];
    const TAVERN:  readonly string[] = ['BILLBOARD_FROG_TAVERN', 'BILLBOARD_ALE_CROAK', 'BILLBOARD_CELLAR_JUMPERS', 'BILLBOARD_CROAK_TAILS'];
    const TOBACCO: readonly string[] = ['BILLBOARD_RED_BOX', 'BILLBOARD_FINE_TOBACCO', 'BILLBOARD_SMOOTH_TASTE', 'BILLBOARD_WRESTLING'];

    const poolFor = (i: number): readonly string[] =>
      i < 200 ? BEAGLE : i < 400 ? TAVERN : TOBACCO;

    const gap = [rInt(15, 30), rInt(20, 40)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      if (absCurve >= 4) { gap[0] = Math.max(gap[0], 8); gap[1] = Math.max(gap[1], 8); continue; }

      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (gap[s] > 0) continue;
        if (i - this.boardLastPlaced[s] < Road.MIN_BOARD_GAP) { gap[s] = rInt(10, 20); continue; }
        const density = absCurve < 1 ? 0.45 : 0.35;
        if (rand() >= density) { gap[s] = rInt(10, 20); continue; }
        const sign   = s === 1 ? +1 : -1;
        const worldX = sign * rInt(2000, 2600);
        plant(seg, pick(poolFor(i)), worldX);
        this.boardLastPlaced[s] = i;
        gap[s] = rInt(30, 55);
      }
    }
  }

  // ── Cookie board placement ────────────────────────────────────────────────

  /**
   * Places portrait cookie boards alongside the road.
   * Entirely separate from plantBillboards() — own PRNG seed, own pool,
   * own gap rules, own worldX range.  Sparser than regular billboards so
   * they feel like a surprise when they appear.
   */
  private plantCookieBoards(): void
  {
    const { rand, rInt, pick } = makePRNG(0xC00C1E5);

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'cookie' as SpriteFamily, worldX, scale: 1 });
    };

    const POOL: readonly string[] = [
      'COOKIE_HAPPY_SMOKING', 'COOKIE_PREMIUM_CIGS',
      'COOKIE_SMOKIN_NOW',    'COOKIE_CIG_RESERVES',
    ];

    // Sparse — only one side at a time, long gaps between appearances.
    const gap = [rInt(40, 80), rInt(50, 90)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      if (absCurve >= 4) { gap[0] = Math.max(gap[0], 12); gap[1] = Math.max(gap[1], 12); continue; }

      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (gap[s] > 0) continue;
        if (rand() >= 0.30) { gap[s] = rInt(25, 50); continue; }
        const sign   = s === 1 ? +1 : -1;
        const worldX = sign * rInt(2000, 2500);
        plant(seg, pick(POOL), worldX);
        gap[s] = rInt(50, 100);   // long gap — these are rare
      }
    }
  }

  // ── Barney board placement ────────────────────────────────────────────────

  /**
   * Places barney boards alongside the road.
   * Entirely separate from all other board types — own PRNG seed, own pool,
   * own gap rules.  Very rare: one side at a time, long gaps.
   */
  private plantBarneyBoards(): void
  {
    const { rand, rInt, pick } = makePRNG(0xBA121E5);

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'barney' as SpriteFamily, worldX, scale: 1 });
    };

    const POOL: readonly string[] = [
      'BARNEY_METAL_TILLETIRE',
      'BARNEY_OUTRUN_PALETTE',
    ];

    const gap = [rInt(60, 120), rInt(70, 130)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      if (absCurve >= 4) { gap[0] = Math.max(gap[0], 15); gap[1] = Math.max(gap[1], 15); continue; }

      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (gap[s] > 0) continue;
        if (rand() >= 0.25) { gap[s] = rInt(30, 60); continue; }
        const sign   = s === 1 ? +1 : -1;
        const worldX = sign * rInt(2000, 2500);
        plant(seg, pick(POOL), worldX);
        gap[s] = rInt(70, 140);   // very long gap — genuinely rare
      }
    }
  }

  // ── Big board placement ───────────────────────────────────────────────────

  /**
   * Places big_boards alongside the road. Extremely rare — ultra-wide landscape
   * billboards that demand attention. Completely independent from all other board types.
   */
  private plantBigBoards(): void
  {
    const { rand, rInt, pick } = makePRNG(0xB163B04D);

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'big' as SpriteFamily, worldX, scale: 1 });
    };

    const POOL: readonly string[] = [
      'BIG_WRESTLING',
    ];

    const gap = [rInt(100, 200), rInt(110, 210)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      if (absCurve >= 4) { gap[0] = Math.max(gap[0], 20); gap[1] = Math.max(gap[1], 20); continue; }

      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (gap[s] > 0) continue;
        if (i - this.boardLastPlaced[s] < Road.MIN_BOARD_GAP) { gap[s] = rInt(50, 100); continue; }
        if (rand() >= 0.20) { gap[s] = rInt(50, 100); continue; }
        const sign   = s === 1 ? +1 : -1;
        const worldX = sign * rInt(2200, 2800);
        plant(seg, pick(POOL), worldX);
        this.boardLastPlaced[s] = i;
        gap[s] = rInt(100, 200);   // extremely rare — big boards dominate visually
      }
    }
  }

  // ── Cactus placement ─────────────────────────────────────────────────────

  /**
   * Sprinkles cactus sprites alongside the road, interspersed with palms and
   * billboards.  Uses a dedicated PRNG seed (0xBADC0FFE) so cactus layout is
   * independent of palm and billboard passes.
   *
   * Placement rules:
   *   - Random gap of 8–25 segments between cactuses on each side.
   *   - Suppressed on tight curves (|curve| ≥ 4).
   *   - WorldX: 1800–3500 wu from road centre (shoulder + verge).
   *   - Random scale 0.6–1.8× so they feel naturally varied in size.
   */
  private plantCactuses(): void
  {
    // TODO (L10): Cactus is a desert/Southwest biome element — thematically
    // inconsistent with this Mediterranean coastal track.  Replace with
    // agave, sea-grape, or bougainvillea if the setting stays Coconut Beach,
    // OR change the track theme to a desert/Arizona setting where cacti fit.
    // For now, cactuses remain as an arcade abstraction.

    // Mulberry32 PRNG — deterministic, independent seed from palms/billboards.
    const { rand, rInt, pick } = makePRNG(0xBADC0FFE);

    const CACTI: string[] = [
      'CACTUS_C1',  'CACTUS_C2',  'CACTUS_C3',  'CACTUS_C4',
      'CACTUS_C5',  'CACTUS_C6',  'CACTUS_C7',  'CACTUS_C8',
      'CACTUS_C9',  'CACTUS_C10', 'CACTUS_C11', 'CACTUS_C12',
      'CACTUS_C13', 'CACTUS_C14', 'CACTUS_C15', 'CACTUS_C16',
      'CACTUS_C17', 'CACTUS_C18', 'CACTUS_C19', 'CACTUS_C20',
      'CACTUS_C21', 'CACTUS_C22',
    ];

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      const scale = 0.8 + rand() * 0.8;   // [0.8, 1.6]
      (seg.sprites ??= []).push({ id, family: 'cactus' as SpriteFamily, worldX, scale });
    };

    const count = this._segments.length;
    // Four independent cooldown tracks per side: near, mid, far, ultra-far
    const gap   = [0, 0, 0, 0, 0, 0, 0, 0];   // [near-L, near-R, mid-L, mid-R, far-L, far-R, ufar-L, ufar-R]

    for (let i = 0; i < count; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      for (let g = 0; g < 8; g++) gap[g] = Math.max(0, gap[g] - 1);

      if (absCurve >= 4) continue;

      for (let s = 0; s < 2; s++)
      {
        const sign = s === 1 ? +1 : -1;

        // Near band: tight to road shoulder (1800–3000)
        if (gap[s] === 0)
        {
          if (rand() < 0.80) {
            const clusterSize = rand() < 0.30 ? 2 : 1;
            for (let c = 0; c < clusterSize; c++)
              plant(seg, pick(CACTI), sign * rInt(1800, 3000));
          }
          gap[s] = rInt(2, 5);
        }

        // Mid band: into the sand (3500–7000)
        if (gap[2 + s] === 0)
        {
          if (rand() < 0.85) {
            const clusterSize = rand() < 0.40 ? rInt(2, 3) : 1;
            for (let c = 0; c < clusterSize; c++)
              plant(seg, pick(CACTI), sign * rInt(3500, 7000));
          }
          gap[2 + s] = rInt(1, 4);
        }

        // Far band: deep desert edge (7000–16000)
        if (gap[4 + s] === 0)
        {
          if (rand() < 0.90) {
            const clusterSize = rInt(1, 3);
            for (let c = 0; c < clusterSize; c++)
              plant(seg, pick(CACTI), sign * rInt(7000, 16000));
          }
          gap[4 + s] = rInt(1, 4);
        }

        // Ultra-far band: screen edges (12000–22000) — small silhouettes
        // sprH ≈ 700 * scale * 400 / worldX. worldX=12000, scale=0.35 → ~8px ✓
        if (gap[6 + s] === 0)
        {
          const clusterSize = rInt(2, 4);
          for (let c = 0; c < clusterSize; c++)
          {
            const worldX = sign * rInt(12000, 22000);
            const scale  = 0.30 + rand() * 0.20;   // [0.30, 0.50]
            (seg.sprites ??= []).push({ id: pick(CACTI), family: 'cactus' as SpriteFamily, worldX, scale });
          }
          gap[6 + s] = rInt(0, 2);
        }
      }
    }
  }

  // ── Turn-sign placement ───────────────────────────────────────────────────

  /**
   * Places groups of six turn-warning signs before each significant curve.
   *
   * Algorithm:
   *  1. Scan segments looking for the START of a new curve — defined as
   *     |curve| crossing above CURVE_THRESHOLD after a run of straight/gentle road.
   *  2. At each detected curve-start at index i, plant signs at the same
   *     three positions as before (i − 3×SPACING, i − 2×SPACING, i − SPACING)
   *     but on BOTH sides of the road — doubling the count from 3 to 6.
   *  3. The sign type matches the curve direction (TURN_RIGHT / TURN_LEFT).
   *  4. A minimum cooldown prevents double-groups for back-to-back curves.
   *  5. Signs are rendered at 1.5× their default world height for visibility.
   */
  private plantSigns(): void
  {
    /** Minimum curve magnitude to trigger warning signs. */
    const CURVE_THRESHOLD = 1.5;
    /** Segments between each sign in the group. */
    const SPACING         = 8;
    /** Minimum segments between groups (avoids re-triggering on a long curve). */
    const GROUP_COOLDOWN  = 40;
    /** WorldX distance from road centre for sign placement (clearly on sand/grass verge). */
    const SIGN_X          = 2500;

    const plant = (seg: RoadSegment, id: string, worldX: number): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'sign' as SpriteFamily, worldX, scale: 1.5 });
    };

    let prevAbsCurve  = 0;
    let lastGroupAt   = -GROUP_COOLDOWN;  // segment index of last placed group

    for (let i = 0; i < this._segments.length; i++)
    {
      const curve    = this._segments[i].curve;
      const absCurve = Math.abs(curve);

      // Detect curve start: magnitude rises past threshold and cooldown has elapsed
      const curveStarting = absCurve >= CURVE_THRESHOLD
                         && prevAbsCurve < CURVE_THRESHOLD
                         && i - lastGroupAt >= GROUP_COOLDOWN;

      if (curveStarting)
      {
        const isRight = curve > 0;
        const signId  = isRight ? 'SIGN_TURN_RIGHT' : 'SIGN_TURN_LEFT';
        // Signs sit on the OUTSIDE of the upcoming curve (where the car would drift).
        // Right bend → outside is the left shoulder; left bend → outside is the right.
        const worldX  = isRight ? -SIGN_X : SIGN_X;

        // 6 signs in a row on the outside shoulder — evenly spaced, counting
        // down from 48 to 8 segments before the corner apex.
        for (let n = 6; n >= 1; n--)
        {
          const si = i - n * SPACING;
          if (si >= 0)
            plant(this._segments[si], signId, worldX);
        }

        lastGroupAt = i;
      }

      prevAbsCurve = absCurve;
    }
  }

  // ── Shrub placement ───────────────────────────────────────────────────────

  /**
   * Scatters shrubs thickly across both sides of the road.
   * Shrubs are small ground-cover plants placed well away from the road edge
   * (worldX 2800–5500) at high density.  They overlap freely — no cross-type
   * gap enforcement is applied and intra-type gaps are short.
   * Uses its own PRNG seed so placement is independent of all other passes.
   */
  private plantShrubs(): void
  {
    const { rand, rInt, pick } = makePRNG(0x5B2B5);

    const plant = (seg: RoadSegment, id: string, worldX: number, scale = 1): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'shrub' as SpriteFamily, worldX, scale });
    };

    const POOL: readonly string[] = [
      'SHRUB_S1', 'SHRUB_S1',   // short scrub — most common
      'SHRUB_S6', 'SHRUB_S6',   // low creosote — wide, very common
      'SHRUB_S2',                // sagebrush — less frequent, taller
    ];

    // ── Pass 1: mid-range shrubs (2500–5000) — dense scatter ─────────────────
    const gap = [rInt(1, 3), rInt(1, 3)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      if (absCurve >= 5) { gap[0] = Math.max(gap[0], 2); gap[1] = Math.max(gap[1], 2); continue; }

      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (gap[s] > 0) continue;
        if (rand() >= 0.88) { gap[s] = rInt(1, 2); continue; }

        const sign  = s === 1 ? +1 : -1;
        const count = rand() < 0.45 ? rInt(2, 3) : 1;
        for (let c = 0; c < count; c++)
          plant(seg, pick(POOL), sign * rInt(2500, 5000));

        gap[s] = rInt(1, 4);
      }
    }

    // ── Pass 2: far shrubs (5000–10000) — thick continuous band ──────────────
    for (let i = 0; i < this._segments.length; i++)
    {
      const seg = this._segments[i];
      if (Math.abs(seg.curve) >= 5) continue;

      for (let s = 0; s < 2; s++)
      {
        const sign  = s === 1 ? +1 : -1;
        const count = rInt(3, 5);
        for (let c = 0; c < count; c++)
          plant(seg, pick(POOL), sign * rInt(5000, 10000), 0.7);
      }
    }

    // ── Pass 3: extreme-edge shrubs (10000–20000) — fills the horizon wall ───
    // Scaled down to ~40% so they read as small distant ground-cover, not giants.
    for (let i = 0; i < this._segments.length; i++)
    {
      const seg = this._segments[i];
      if (Math.abs(seg.curve) >= 5) continue;

      for (let s = 0; s < 2; s++)
      {
        const sign  = s === 1 ? +1 : -1;
        const count = rInt(4, 7);
        for (let c = 0; c < count; c++)
          plant(seg, pick(POOL), sign * rInt(10000, 20000), 0.4);
      }
    }

    // ── Pass 4: screen-edge shrubs (12000–22000) — covers the bare far desert ─
    // sprH ≈ worldH(~600) * scale * halfH / worldX.
    // worldX=12000, scale=0.35 → ~7px;  worldX=18000, scale=0.45 → ~6px.
    // Dense (every segment, 5–8 per side) to fill the edge band continuously.
    for (let i = 0; i < this._segments.length; i++)
    {
      const seg = this._segments[i];
      if (Math.abs(seg.curve) >= 5) continue;

      for (let s = 0; s < 2; s++)
      {
        const sign  = s === 1 ? +1 : -1;
        const count = rInt(5, 8);
        for (let c = 0; c < count; c++)
          plant(seg, pick(POOL), sign * rInt(12000, 22000), 0.35 + rand() * 0.15);
      }
    }
  }

  // ── House placement ───────────────────────────────────────────────────────

  /**
   * Scatters houses and buildings along both sides of the road.
   *
   * All 25 sprite varieties are drawn from a single mixed pool so types
   * are distributed randomly across the whole track rather than bunched
   * by section.  The seed is re-rolled each page load (Date.now()) so
   * the layout is different every run.
   *
   * Facing rule — all sprites have their facade pointing RIGHT in the sheet:
   *   Left side (worldX < 0)  → as-is, facade already faces road centre.
   *   Right side (worldX > 0) → flipX=true, mirrors sprite to face left.
   *
   * Text-bearing sprites (SHOP, BAKERY, SURF, CAFE, ARCADE) must NEVER be
   * flipped — they only appear on the LEFT side where reading is correct.
   *
   * Distance: 3000–5500 wu primary, 5500–9000 wu for background depth.
   * Gap: 10–30 segments — buildings feel like a continuous roadside presence.
   */
  private plantHouses(): void
  {
    const { rand, rInt, pick } = makePRNG(0xD1CE5EED);

    const plant = (seg: RoadSegment, id: string, worldX: number, flipX = false): void =>
    {
      (seg.sprites ??= []).push({ id, family: 'house' as SpriteFamily, worldX, flipX, scale: 1 });
    };

    // Text on facade — left side only, never flip.
    const TEXT: readonly string[] = [
      'HOUSE_SHOP', 'HOUSE_BAKERY', 'HOUSE_SURF', 'HOUSE_CAFE', 'HOUSE_ARCADE',
    ];

    // No legible text — safe to flip and place on either side.
    const SAFE: readonly string[] = [
      'HOUSE_PURPLE', 'HOUSE_TEAL', 'HOUSE_YELLOW', 'HOUSE_GREEN', 'HOUSE_PINK',
    ];

    // LEFT pool = TEXT + SAFE; RIGHT pool = SAFE only.
    const LEFT:  readonly string[] = [...TEXT, ...SAFE];
    const RIGHT: readonly string[] = SAFE;

    const gap = [rInt(15, 35), rInt(20, 45)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg      = this._segments[i];
      const absCurve = Math.abs(seg.curve);

      if (absCurve >= 3) { gap[0] = Math.max(gap[0], 10); gap[1] = Math.max(gap[1], 10); continue; }

      gap[0] = Math.max(0, gap[0] - 1);
      gap[1] = Math.max(0, gap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (gap[s] > 0) continue;
        if (rand() >= 0.70) { gap[s] = rInt(12, 25); continue; }

        const isLeft = s === 0;
        const sign   = isLeft ? -1 : +1;
        const pool   = isLeft ? LEFT : RIGHT;

        plant(seg, pick(pool), sign * rInt(3000, 5500), !isLeft);

        // 40% chance: second building behind for depth
        if (rand() < 0.40)
          plant(seg, pick(SAFE), sign * rInt(5500, 9000), !isLeft);

        gap[s] = rInt(20, 45);
      }
    }

    // ── Ultra-far pass: adobe + desert structures at screen edges ─────────────
    // sprH ≈ worldH * scale * halfH / worldX (at screen edge, sc1 ≈ 1/worldX).
    // worldH ≈ 1800, halfH ≈ 400: worldX=10000 scale=0.25 → ~18px ✓
    //                              worldX=20000 scale=0.35 → ~13px ✓
    // Gap 4–12 segs so they feel like scattered distant settlements.
    const DISTANT: readonly string[] = [
      'HOUSE_ADOBE_1', 'HOUSE_ADOBE_2', 'HOUSE_ADOBE_3', 'HOUSE_ADOBE_4',
      'HOUSE_ADOBE_5', 'HOUSE_ADOBE_6', 'HOUSE_ADOBE_7', 'HOUSE_ADOBE_8',
      'HOUSE_ADOBE_9', 'HOUSE_ADOBE_10',
      'HOUSE_DOME',    'HOUSE_TENT_L',  'HOUSE_HUT',     'HOUSE_TENT_S',  'HOUSE_BUNKER',
    ];

    const farGap = [rInt(4, 10), rInt(5, 12)];

    for (let i = 0; i < this._segments.length; i++)
    {
      const seg = this._segments[i];
      if (Math.abs(seg.curve) >= 4) continue;

      farGap[0] = Math.max(0, farGap[0] - 1);
      farGap[1] = Math.max(0, farGap[1] - 1);

      for (let s = 0; s < 2; s++)
      {
        if (farGap[s] > 0) continue;
        if (rand() >= 0.80) { farGap[s] = rInt(3, 8); continue; }

        const sign  = s === 1 ? +1 : -1;
        const scale = 0.60 + rand() * 0.60;   // [0.60, 1.20] — visible distant buildings
        (seg.sprites ??= []).push({ id: pick(DISTANT), family: 'house' as SpriteFamily, worldX: sign * rInt(10000, 20000), scale, stretchX: 1.25 });

        farGap[s] = rInt(4, 12);
      }
    }
  }

  // ── Lookup ────────────────────────────────────────────────────────────────

  /**
   * Returns the segment the player is currently standing on.
   *
   * playerZ increases as the player moves forward.  We divide by SEGMENT_LENGTH
   * to find which "slot" the player is in, then wrap around using modulo so the
   * track loops seamlessly when the player reaches the end.
   *
   * @param playerZ - Player's current depth position in world units.
   * @returns The RoadSegment beneath the player.
   */
  /**
   * Returns the index of the segment beneath a world-space Z position.
   * Handles both the +n wrap guard (so negative Z never yields -1) and
   * the modulo wrap for track looping — the single authoritative formula.
   *
   * @param z - World-space depth position (may be negative before first frame).
   * @returns Segment index in [0, count).
   */
  findSegmentIndex(z: number): number
  {
    const n = this.count;
    return ((Math.floor(z / SEGMENT_LENGTH) % n) + n) % n;
  }

  findSegment(playerZ: number): RoadSegment
  {
    return this._segments[this.findSegmentIndex(playerZ)];
  }

  // ── Static factory: load from pre-built data ──────────────────────────────

  /**
   * Constructs a Road from pre-serialized segment data generated at build time.
   *
   * Bypasses all nine plant passes (palm, billboard, cactus, house, etc.) that
   * normally run synchronously on the main thread during `new Road()`.  On
   * mid-range mobile these passes take 50–200 ms.  Loading a pre-built array
   * instead makes startup near-instant (M15).
   *
   * The generate-road.ts build script produces src/road-data.ts; game.ts
   * imports that module and calls Road.fromData(ROAD_DATA).
   *
   * @param data - Array of SerializedSegment objects from road-data.ts.
   * @returns A fully-initialised Road ready for the game loop.
   */
  static fromData(data: SerializedSegment[]): Road
  {
    const road = Object.create(Road.prototype) as Road;
    road._segments = data.map(d => ({
      index:   d.index,
      curve:   d.curve,
      color:   d.color,
      sprites: d.sprites.length > 0 ? d.sprites : undefined,
      p1:      makeProjectedPoint(d.p1z, d.p1y),
      p2:      makeProjectedPoint(d.p2z, d.p2y),
    }));
    return road;
  }

  /**
   * Serializes all segments to the minimal format understood by fromData().
   * Called by scripts/generate-road.ts at build time — not used at runtime.
   */
  toJSON(): SerializedSegment[]
  {
    return this._segments.map(s => ({
      index:   s.index,
      curve:   s.curve,
      color:   s.color,
      sprites: s.sprites ?? [],
      p1y:     s.p1.world.y,
      p1z:     s.p1.world.z,
      p2y:     s.p2.world.y,
      p2z:     s.p2.world.z,
    }));
  }
}
