/**
 * sprites.ts
 *
 * Sprite metadata and the SpriteLoader helper used by the renderer.
 *
 * Two sprite sheets are used:
 *   sprites/assets/cars/player_car_sprites_1x.png  — 37-frame Ferrari Testarossa animation strip.
 *   sprites/assets/sprite_sheet_transparent.png    — roadside objects (palm trees, etc.).
 *
 * The background colour of the roadside sheet has been zeroed out offline so
 * no runtime colour-keying is needed — straight alpha blending works correctly.
 */

// ── Rectangle type ────────────────────────────────────────────────────────────

/**
 * A rectangular region within a sprite sheet, in sheet pixels.
 * Used to tell drawImage() exactly which sub-image to copy.
 */
export interface SpriteRect
{
  x: number;
  y: number;
  w: number;
  h: number;
}

// ── Player car ────────────────────────────────────────────────────────────────

/**
 * The car sprite sheet is a single horizontal strip of 37 equal-width frames.
 * Frame 0  = car turned 90° left (hard left steer).
 * Frame 18 = car pointing straight ahead (neutral).
 * Frame 36 = car turned 90° right (hard right steer).
 *
 * Frames 1–17: left turns (sourced from left.png).
 * Frames 19–35: right turns (sourced from right.png, mirrored).
 *
 * At runtime, steerAngle (-1…+1) maps to a frame index via:
 *   index = Math.round(steerAngle * CAR_SPRITE_CENTER * 0.6) + CAR_SPRITE_CENTER
 * The 0.6 cap prevents the nose from pointing sideways at full lock.
 */
export const CAR_SPRITE_FRAME_W = 312;   // pixels per frame
export const CAR_SPRITE_FRAME_H = 149;   // pixels per frame
export const CAR_SPRITE_TOTAL   = 37;    // total frames in the strip
export const CAR_SPRITE_CENTER  = 18;    // index of the straight-ahead frame

/**
 * Returns the source rectangle for a given frame index.
 * Clamps index into the valid range [0, 36] so out-of-bounds calls are safe.
 *
 * @param index - Frame index in [0, CAR_SPRITE_TOTAL - 1].
 * @returns SpriteRect describing where that frame lives in the sheet.
 */
export function carFrameRect(index: number): SpriteRect
{
  const i = Math.max(0, Math.min(CAR_SPRITE_TOTAL - 1, index));
  return { x: i * CAR_SPRITE_FRAME_W, y: 0, w: CAR_SPRITE_FRAME_W, h: CAR_SPRITE_FRAME_H };
}

/**
 * Per-frame horizontal pivot offset, in sprite pixels from the cell centre.
 *
 * Because the car is not always centred within its bounding box (the body
 * shifts left or right as the car steers), a raw centre-of-cell placement
 * makes the rear axle wobble left and right across the screen.
 *
 * Positive offset → the pivot is to the LEFT of the cell centre →
 *   the renderer shifts the draw position rightward to compensate.
 *
 * Generated offline by sprites/build_sprite_sheet.py.
 */
export const CAR_PIVOT_OFFSETS: number[] = [
  3, -13, -12, -41, -41, -32, -31, -29, -33, -36, -36, -25, -28,
  -3, -10, -9, -9, 6, 3, 3, 9, 12, 12, 5, 30, 28, 38, 38,
  36, 31, 33, 34, 43, 43, 14, 15, -2,
];

// ── Roadside sprites ──────────────────────────────────────────────────────────

/**
 * Valid roadside sprite names.
 * All nine palm varieties are laid out in sprites/assets/palm_sheet.png.
 * Built by sprites/build_palm_sheet.py — regenerate if source PNGs change.
 *
 *   T1  Straight  — full-grown, vertical trunk
 *   T2L Bent Left — trunk leans left (plant on right side of road)
 *   T2R Bent Right— trunk leans right (plant on left side of road)
 *   T3  Young     — shorter, slender trunk
 *   T4  Fruiting  — clustered coconuts at crown
 *   T6  Luxuriant — dense wide canopy
 *   T7  Slender   — extra tall, narrow silhouette
 *   T8  Medium    — compact mid-size
 *  T10  Large     — broad, imposing crown
 */
export type SpriteId =
  | 'PALM_T1_STRAIGHT'
  | 'PALM_T2_BENT_LEFT'
  | 'PALM_T2_BENT_RIGHT'
  | 'PALM_T3_YOUNG'
  | 'PALM_T4_FRUITING'
  | 'PALM_T6_LUXURIANT'
  | 'PALM_T7_SLENDER'
  | 'PALM_T8_MEDIUM'
  | 'PALM_T10_LARGE';

/**
 * Source rectangles for each palm within sprites/assets/palm_sheet.png.
 * Generated by sprites/build_palm_sheet.py — sheet is 1246×224 px.
 */
export const SPRITE_RECTS: Record<SpriteId, SpriteRect> =
{
  PALM_T1_STRAIGHT:  { x:    4, y:   4, w: 133, h: 216 },
  PALM_T2_BENT_LEFT: { x:  145, y:   9, w: 153, h: 205 },
  PALM_T2_BENT_RIGHT:{ x:  306, y:   9, w: 153, h: 205 },
  PALM_T3_YOUNG:     { x:  467, y:  32, w: 103, h: 160 },
  PALM_T4_FRUITING:  { x:  578, y:   6, w: 133, h: 212 },
  PALM_T6_LUXURIANT: { x:  719, y:   9, w: 152, h: 205 },
  PALM_T7_SLENDER:   { x:  879, y:   4, w: 114, h: 215 },
  PALM_T8_MEDIUM:    { x: 1001, y:  34, w: 107, h: 156 },
  PALM_T10_LARGE:    { x: 1116, y:  26, w: 126, h: 171 },
};

/**
 * Real-world height of each palm in world units.
 * The renderer multiplies this by the perspective scale to get pixel height.
 * At 30 segments ahead: sprH ≈ worldH × 0.042 at a 600 px canvas.
 */
export const SPRITE_WORLD_HEIGHT: Record<SpriteId, number> =
{
  PALM_T1_STRAIGHT:  1900,
  PALM_T2_BENT_LEFT: 1800,
  PALM_T2_BENT_RIGHT:1800,
  PALM_T3_YOUNG:     1300,
  PALM_T4_FRUITING:  1700,
  PALM_T6_LUXURIANT: 2100,
  PALM_T7_SLENDER:   2300,
  PALM_T8_MEDIUM:    1600,
  PALM_T10_LARGE:    2000,
};

// ── Loader ────────────────────────────────────────────────────────────────────

/**
 * Wraps an HTMLImageElement and loads a sprite sheet from a URL.
 *
 * Usage:
 *   const sheet = new SpriteLoader('sprites/my_sheet.png');
 *   await sheet.ready;          // optional — isReady() works without awaiting
 *   sheet.draw(ctx, rect, ...); // no-op if image hasn't loaded yet
 */
export class SpriteLoader
{
  private img: HTMLImageElement | null = null;

  /** Resolves when the image has finished loading, or rejects on error. */
  readonly ready: Promise<void>;

  /**
   * Begins loading the image at the given URL.
   *
   * @param src - Path to the sprite sheet, relative to the HTML page.
   */
  constructor(src: string)
  {
    this.ready = new Promise<void>((resolve, reject) =>
    {
      const img    = new Image();
      img.onload   = () => { this.img = img; resolve(); };
      img.onerror  = reject;
      img.src      = src;
    });
  }

  /**
   * Returns true once the image has loaded and is ready to draw.
   * The renderer checks this each frame so it can skip drawing if not ready.
   */
  isReady(): boolean
  {
    return this.img !== null;
  }

  /**
   * Copies a sub-rectangle from the sprite sheet to the canvas.
   * Silently does nothing if the image hasn't loaded yet, or if the
   * destination size is zero or negative (which would throw a browser error).
   *
   * @param ctx  - The 2-D canvas context to draw into.
   * @param rect - Source rectangle within the sprite sheet.
   * @param dx   - Destination left edge in canvas pixels.
   * @param dy   - Destination top edge in canvas pixels.
   * @param dw   - Destination width in canvas pixels.
   * @param dh   - Destination height in canvas pixels.
   */
  draw(
    ctx: CanvasRenderingContext2D,
    rect: SpriteRect,
    dx: number, dy: number,
    dw: number, dh: number,
  ): void
  {
    if (!this.img || dw <= 0 || dh <= 0) return;
    ctx.drawImage(this.img, rect.x, rect.y, rect.w, rect.h, dx, dy, dw, dh);
  }
}
